#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
    deb-systemd-helper --user unmask 'rldyour-sysinfod.socket' >/dev/null || true
fi

if [ "$1" = "purge" ]; then
    deb-systemd-helper --user purge 'rldyour-sysinfod.socket' >/dev/null || true
    deb-systemd-helper --user unmask 'rldyour-sysinfod.socket' >/dev/null || true
fi

exit 0
